version: "3.9"

services:
  backend:
    build:
      context: ./backend
    image: backend-image
    ports:
      - 2021:8000
  frontend:
    build:
      context: ./frontend
    image: frontend-image
    ports:
      - 2020:80